template-file-path: templates/root.yaml

parameters:
  EnvironmentName: photo-uploader
  TemplateBucketName: photo-uploader-deploy-artifacts-288761749193-eu-central-1
  TemplateVersion: 97fffc535c3cd3af542c991708660df1f14478dd
  AccessLogsBucketName: photo-uploader-access-logs-288761749193-eu-central-1
  ServiceDesiredCount: 0

tags: {}
